### PR TITLE
New feature: Inbound RF amplitude measurement

### PR DESCRIPTION
**Pull request by TokugawaHeavyIndustries**
New functionality implemented - inbound RF amplitude measurement

1. New window in configuration dialog for UI settings (configuration file version is bumped to v3)
2. Toggle text-based RMS label on/off
3. Select type of visual chart/graph (currently implemented: none or waveform generated by QCustomPlot)
4. Ability to measure amplitude in all capture formats (16 bit, 10 bit packed, 10 bit packed decimated)
5. Extra math converting packed data to unpacked is disabled when no amplitude features are selected
6. Added attribution for QCustomPlot in `aboutdialog.ui`

### CODE REVIEW

**Comment by TokugawaHeavyIndustries** [comment]
This requires `qt6-multimedia-dev`. Currently testing qt5. QtGraph is unused and will be removed soon

**Comment by JonasCz** [comment]
For any other C++ / Cmake newbies like me, who wanted to try this feature, but was struggling to get it to compile, you need to modify the file: `/Linux-Application/DomesdayDuplicator/CMakeLists.txt`

Add `amplitudemeasurement.cpp` & `qcustomplot.cpp` to the list under `set(DomesdayDuplicator_SOURCES`, and add `Qt6::Multimedia` under `target_link_libraries(DomesdayDuplicator PRIVATE`

I also changed line in `/Linux-Application/CMakeLists.txt` to `find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Gui Widgets SerialPort Multimedia)` to add the Multimedia package. As per above, `qt6-multimedia-dev` is needed.

**Comment by TokugawaHeavyIndustries** [comment]
Quick note that `build-essential` is required for cmake on Ubuntu 22.04

**Comment by TokugawaHeavyIndustries** [comment]
Updated the workflow to include needed dependencies (qt6-multimedia-dev) and to remove Qt5 checks.  Note that the method used to process the inbound data uses `QAudioSource` which does not exist in Qt5, so this release will require Qt6 and cmake.

**Pull request merged**
